# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

from ...apimachinery.pkg.apis.meta import v1


class DeviceAttribute(BaseModel):
    bool_: bool | None = Field(None, alias='bool')
    """
    BoolValue is a true/false value.
    """
    int_: int | None = Field(None, alias='int')
    """
    IntValue is a number.
    """
    string: str | None = None
    """
    StringValue is a string.
    """
    version: str | None = None
    """
    VersionValue is a semantic version according to semver.org spec 2.0.0.
    """


class Device(BaseModel):
    name: str
    """
    Name is a unique identifier among all devices managed by the driver.
    """
    attributes: dict[str, DeviceAttribute] | None = None
    """
    Attributes defines the set of attributes for this device.
    """


class Spec(BaseModel):
    devices: list[Device] | None = None
    """
    Devices lists the devices in this resource slice.
    """


class ResourceSlice(BaseModel):
    apiVersion: Literal['resource.k8s.io/v1'] | None = 'resource.k8s.io/v1'
    """
    APIVersion defines the versioned schema of this representation of an object.
    """
    kind: Literal['ResourceSlice'] | None = 'ResourceSlice'
    """
    Kind is a string value representing the REST resource this object represents.
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata.
    """
    spec: Spec
    """
    Contents of the ResourceSlice.
    """
